### ISSUE TITLE
NoneType error

### ISSUE THREAD

**Issue by danielmitrov** [yuvalsteuer/Calculator#1]
When the last operand is greater than 9, I get the following error:
`'NoneType' object has no attribute 'lexeme'`

For example:
`5 * 10` - doesn't work
`5 * 10 * 1` - works
`7 + 2 + 25` - doesn't work
`7 + 2 + 25 + 5` - works

**Comment by yuvalsteuer-personal** [comment]
Fixed, Problem was that the last token wasn't included in a case where the last token in the token stream was to be a multiple digit number.
